# Generated by Django 2.2.4 on 2021-06-22 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redSocial', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='context',
            new_name='content',
        ),
    ]
