# Generated by Django 2.2.4 on 2021-06-22 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redSocial', '0002_auto_20210622_0240'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='perrito.jpg', upload_to=''),
        ),
    ]
