# Generated by Django 2.2.4 on 2021-06-23 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redSocial', '0003_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='uwu.png', upload_to=''),
        ),
    ]
