# Generated by Django 2.2.4 on 2021-06-25 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redSocial', '0004_auto_20210623_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='uwu.png', upload_to='media/%Y/%m/%d'),
        ),
    ]
